# Generated by Django 5.0.4 on 2025-12-19 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRelevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('relevamiento', 'Estudio de Relevamiento'), ('actualizacion', 'Estudio de Actualización')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_asignacion_sig', 'Pendiente de Digitalizador'), ('asignado_a_digitalizador', 'Asignado a Digitalizador'), ('en_proceso_digitalizacion', 'En Proceso de Digitalización'), ('pendiente_asignacion_analista', 'Pendiente de Análisis'), ('en_analisis', 'En Análisis'), ('rechazado', 'Rechazado'), ('aprobado_para_campo', 'Aprobado para Campo'), ('en_ejecucion_campo', 'En Ejecución de Campo')], default='pendiente_asignacion_sig', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_relevamiento', to='core.colonia')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de relevamiento',
                'verbose_name_plural': 'Solicitudes de relevamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRelevamientoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previo', models.CharField(max_length=50)),
                ('nuevo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='gerencia.solicitudrelevamiento')),
            ],
            options={
                'verbose_name': 'Auditoría - Solicitud Relevamiento',
                'verbose_name_plural': 'Auditorías - Solicitudes Relevamiento',
                'ordering': ['-fecha'],
            },
        ),
    ]
