# Generated by Django 5.0.4 on 2025-12-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='tipo',
            field=models.CharField(choices=[('relevamiento', 'Estudio de Relevamiento'), ('actualizacion', 'Estudio de Actualización')], editable=False, max_length=20),
        ),
    ]
