# Generated by Django 5.0.4 on 2026-01-06 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_alter_solicitudrelevamiento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='analista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_analista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='digitalizador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_digitalizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_asignacion_analista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_asignacion_digitalizador',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente_asignacion_sig', 'Pendiente de Digitalizador'), ('asignado_a_digitalizador', 'Asignado a Digitalizador'), ('en_proceso_digitalizacion', 'En Proceso de Digitalización'), ('pendiente_revision_sig', 'Pendiente de Revisión SIG'), ('en_revision_sig', 'En Revisión SIG'), ('pendiente_asignacion_analista', 'Pendiente de Análisis'), ('en_analisis', 'En Análisis'), ('rechazado', 'Rechazado'), ('aprobado_para_campo', 'Aprobado para Campo'), ('en_ejecucion_campo', 'En Ejecución de Campo')], default='pendiente_asignacion_sig', max_length=30),
        ),
    ]
