# Generated by Django 5.0.4 on 2026-01-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_flujotrabajo'),
        ('gerencia', '0003_solicitudrelevamiento_analista_asignado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrelevamientoaudit',
            options={'ordering': ['-fecha'], 'verbose_name': 'Auditoría'},
        ),
        migrations.RemoveField(
            model_name='solicitudrelevamiento',
            name='analista_asignado',
        ),
        migrations.RemoveField(
            model_name='solicitudrelevamiento',
            name='digitalizador_asignado',
        ),
        migrations.RemoveField(
            model_name='solicitudrelevamiento',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='solicitudrelevamiento',
            name='fecha_asignacion_analista',
        ),
        migrations.RemoveField(
            model_name='solicitudrelevamiento',
            name='fecha_asignacion_digitalizador',
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_inicio_etapa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='grupo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_actuales', to='administrador.grupo'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='tiempo_analisis',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo total Análisis'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='tiempo_digitalizacion',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo total SIG'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='tiempo_total',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo total proceso'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente_asignacion_sig', 'Pendiente de Asignación SIG'), ('asignado_a_digitalizador', 'Asignado a Digitalizador'), ('en_proceso_digitalizacion', 'En Proceso de Digitalización'), ('pendiente_revision_sig', 'Pendiente de Revisión SIG'), ('pendiente_asignacion_analista', 'Pendiente de Asignación Análisis'), ('en_proceso_analisis', 'En Proceso de Análisis'), ('rechazado', 'Rechazado'), ('aprobado_para_campo', 'Aprobado para Campo'), ('en_ejecucion_campo', 'En Ejecución de Campo'), ('finalizado', 'Finalizado')], default='pendiente_asignacion_sig', max_length=30),
        ),
    ]
