# Generated by Django 5.0.4 on 2026-01-13 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_flujotrabajo'),
        ('core', '0002_colonia_tiene_relevamiento'),
        ('gerencia', '0004_alter_solicitudrelevamientoaudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrelevamiento',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('cambiar_estado', 'Puede cambiar el estado de la solicitud'), ('reasignar_grupo', 'Puede reasignar el grupo de la solicitud'), ('ver_estadisticas', 'Puede ver estadísticas de las solicitudes')], 'verbose_name': 'Solicitud de relevamiento', 'verbose_name_plural': 'Solicitudes de relevamiento'},
        ),
        migrations.AlterModelOptions(
            name='solicitudrelevamientoaudit',
            options={'ordering': ['-fecha'], 'verbose_name': 'Auditoría de solicitud', 'verbose_name_plural': 'Auditorías de solicitudes'},
        ),
        migrations.RemoveField(
            model_name='solicitudrelevamientoaudit',
            name='nuevo',
        ),
        migrations.RemoveField(
            model_name='solicitudrelevamientoaudit',
            name='previo',
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_aprobacion_campo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación para campo'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_fin_campo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin de campo'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_inicio_campo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de campo'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='tiempo_campo',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo total Campo'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamientoaudit',
            name='campo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Campo modificado'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamientoaudit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamientoaudit',
            name='valor_anterior',
            field=models.TextField(blank=True, verbose_name='Valor anterior'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamientoaudit',
            name='valor_nuevo',
            field=models.TextField(blank=True, verbose_name='Valor nuevo'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_relevamiento', to='core.colonia', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente_asignacion_sig', 'Pendiente de Asignación SIG'), ('asignado_a_digitalizador', 'Asignado a Digitalizador'), ('en_proceso_digitalizacion', 'En Proceso de Digitalización'), ('pendiente_revision_sig', 'Pendiente de Revisión SIG'), ('pendiente_asignacion_analista', 'Pendiente de Asignación Análisis'), ('pendiente_revision_analista', 'Pendiente de Revisión Análisis'), ('en_proceso_analisis', 'En Proceso de Análisis'), ('rechazado', 'Rechazado'), ('pendiente_aprobacion_campo', 'Pendiente Aprobación para Campo'), ('aprobado_para_campo', 'Aprobado para Campo'), ('asignado_coordinacion', 'Asignado a Coordinación'), ('preparacion_campo', 'En Preparación de Campo'), ('en_ejecucion_campo', 'En Ejecución de Campo'), ('pendiente_cierre', 'Pendiente de Cierre'), ('finalizado', 'Finalizado')], max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='fecha_inicio_etapa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de etapa actual'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='grupo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_actuales', to='administrador.grupo', verbose_name='Grupo asignado'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='tipo',
            field=models.CharField(choices=[('relevamiento', 'Estudio de Relevamiento'), ('actualizacion', 'Estudio de Actualización')], editable=False, max_length=20, verbose_name='Tipo de estudio'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamientoaudit',
            name='cambiado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamientoaudit',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamientoaudit',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamientoaudit',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='gerencia.solicitudrelevamiento', verbose_name='Solicitud'),
        ),
        migrations.AddIndex(
            model_name='solicitudrelevamientoaudit',
            index=models.Index(fields=['solicitud', 'fecha'], name='gerencia_so_solicit_e11779_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudrelevamientoaudit',
            index=models.Index(fields=['campo', 'fecha'], name='gerencia_so_campo_bb13b8_idx'),
        ),
    ]
