# Generated by Django 5.0.4 on 2026-01-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0005_alter_solicitudrelevamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='baja', max_length=10, verbose_name='Prioridad'),
        ),
    ]
