# Generated by Django 5.0.4 on 2026-01-31 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0006_solicitudrelevamiento_prioridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='coordinador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_coordinadas', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador asignado'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='fecha_generacion_orden',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha generación orden'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='numero_orden_trabajo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Orden de Trabajo'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='relevadores_asignados',
            field=models.ManyToManyField(blank=True, related_name='relevamientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Relevadores asignados'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='ultima_asignacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimas_asignaciones', to=settings.AUTH_USER_MODEL, verbose_name='Última asignación por'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='usuario_analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_analizadas', to=settings.AUTH_USER_MODEL, verbose_name='Analista asignado'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='usuario_digitalizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_digitalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Digitalizador asignado'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='usuario_generador_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generador de orden'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente_asignacion_sig', 'Pendiente de Asignación SIG'), ('asignado_a_digitalizador', 'Asignado a Digitalizador'), ('en_proceso_digitalizacion', 'En Proceso de Digitalización'), ('pendiente_revision_sig', 'Pendiente de Revisión SIG'), ('rechazado', 'Rechazado'), ('pendiente_asignacion_analista', 'Pendiente de Asignación Análisis'), ('asignado_a_analista', 'Asignado a Analista'), ('pendiente_revision_analista', 'Pendiente de Revisión Análisis'), ('en_proceso_analisis', 'En Proceso de Análisis'), ('pendiente_aprobacion_campo', 'Pendiente Aprobación para Campo'), ('aprobado_para_campo', 'Aprobado para Campo'), ('orden_trabajo_generada', 'Orden de Trabajo Generada'), ('asignado_relevadores', 'Asignado a Relevadores'), ('preparacion_campo', 'En Preparación de Campo'), ('en_ejecucion_campo', 'En Ejecución de Campo'), ('pendiente_cierre', 'Pendiente de Cierre'), ('finalizado', 'Finalizado')], max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas_actualmente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado actualmente'),
        ),
    ]
