# Generated by Django 5.0.4 on 2026-02-01 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0008_alter_solicitudrelevamiento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='cambiado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
