# Generated by Django 5.0.4 on 2026-02-12 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0010_alter_solicitudrelevamiento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='choferes',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_chofer', to=settings.AUTH_USER_MODEL, verbose_name='Choferes'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='coordinador_campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_coordinadas_campo', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador de campo'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='subcoordinadores',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_subcoordinadas', to=settings.AUTH_USER_MODEL, verbose_name='Subcoordinadores'),
        ),
    ]
