# Generated by Django 5.0.4 on 2026-02-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0011_solicitudrelevamiento_choferes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='numero_orden_trabajo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Orden de Trabajo'),
        ),
    ]
