# Generated by Django 5.0.4 on 2026-02-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0012_alter_solicitudrelevamiento_numero_orden_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('relevamiento', 'Relevamiento'), ('sig', 'SIG'), ('analisis', 'Análisis'), ('expedientes', 'Expedientes')], max_length=50, verbose_name='Grupo')),
                ('tipo_objetivo', models.CharField(choices=[('colonias_relevadas', 'Colonias Relevadas'), ('planos_aprobados', 'Planos Aprobados'), ('ingreso_catastro', 'Ingresos a Catastro Nacional'), ('informes_finales', 'Informes Finales Presentados'), ('adjudicaciones', 'Adjudicaciones'), ('expedientes_completados', 'Expedientes Completados para Titulación'), ('expedientes_titulados', 'Expedientes Titulados')], max_length=50, verbose_name='Tipo de Objetivo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('meta', models.IntegerField(help_text='Cantidad objetivo a alcanzar en el año', verbose_name='Meta')),
                ('avance_actual', models.IntegerField(default=0, help_text='Cantidad actual alcanzada', verbose_name='Avance Actual')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['-anio', 'grupo', 'tipo_objetivo'],
                'indexes': [models.Index(fields=['anio', 'grupo'], name='gerencia_ob_anio_3fc0fc_idx'), models.Index(fields=['activo', 'anio'], name='gerencia_ob_activo_b08010_idx')],
                'unique_together': {('grupo', 'tipo_objetivo', 'anio')},
            },
        ),
    ]
