# Generated by Django 5.0.4 on 2026-02-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_flujotrabajo'),
        ('gerencia', '0013_objetivo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='objetivo',
            new_name='gerencia_ob_anio_e4d1d9_idx',
            old_name='gerencia_ob_anio_3fc0fc_idx',
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='grupo',
            field=models.ForeignKey(help_text='Grupo organizacional responsable del objetivo', on_delete=django.db.models.deletion.PROTECT, related_name='objetivos', to='administrador.grupo', verbose_name='Grupo'),
        ),
    ]
