# Generated by Django 5.0.4 on 2026-02-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_flujotrabajo'),
        ('gerencia', '0014_rename_gerencia_ob_anio_3fc0fc_idx_gerencia_ob_anio_e4d1d9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos', to='administrador.grupo', verbose_name='Grupo'),
        ),
    ]
