# Generated by Django 5.0.4 on 2026-02-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0015_alter_objetivo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha límite para alcanzar la meta', null=True, verbose_name='Fecha Final'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio del objetivo', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='anio',
            field=models.IntegerField(help_text='Año del objetivo (derivado de fecha_fin)', verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='meta',
            field=models.IntegerField(help_text='Cantidad objetivo a alcanzar en el periodo', verbose_name='Meta'),
        ),
    ]
