# Generated by Django 5.0.4 on 2026-02-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_remove_grupo_tipos_objetivo'),
        ('gerencia', '0018_completar_cambio_tipo_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='actualizacion_terminado',
            field=models.BooleanField(default=False, help_text='Marca si la actualización fue terminada o completada.', verbose_name='Actualización Terminada'),
        ),
        migrations.AddField(
            model_name='solicitudrelevamiento',
            name='relevamiento_terminado',
            field=models.BooleanField(default=False, help_text='Marca si el relevamiento fue terminado o completado.', verbose_name='Relevamiento Terminado'),
        ),
        migrations.AlterField(
            model_name='solicitudrelevamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente_asignacion_sig', 'Pendiente de Asignación SIG'), ('asignado_a_digitalizador', 'Asignado a Digitalizador'), ('en_proceso_digitalizacion', 'En Proceso de Digitalización'), ('pendiente_revision_sig', 'Pendiente de Revisión SIG'), ('rechazado', 'Rechazado'), ('pendiente_asignacion_analista', 'Pendiente de Asignación Análisis'), ('asignado_a_analista', 'Asignado a Analista'), ('en_proceso_analisis', 'En Proceso de Análisis'), ('pendiente_revision_analista', 'Pendiente de Revisión Análisis'), ('aprobado_para_campo', 'Aprobado para Campo'), ('asignado_coordinacion', 'Asignado a Coordinación'), ('orden_trabajo_generada', 'Orden de Trabajo Generada'), ('asignado_relevadores', 'Asignado a Relevadores'), ('en_ejecucion_campo', 'En Ejecución de Campo'), ('pendiente_cierre', 'Pendiente de Cierre'), ('relevamiento_finalizado', 'Relevamiento Finalizado'), ('actualizacion_finalizada', 'Actualización Finalizada')], max_length=30, verbose_name='Estado'),
        ),

    ]
