# Generated by Django 5.0.4 on 2026-02-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_remove_grupo_tipos_objetivo'),
        ('gerencia', '0020_alter_solicitudrelevamiento_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrelevamiento',
            name='usuario_digitalizador',
        )
    ]
