# Generated by Django 5.0.4 on 2026-02-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_remove_grupo_tipos_objetivo'),
        ('gerencia', '0021_remove_solicitudrelevamiento_usuario_digitalizador_and_more'),
    ]

 