# Generated by Django 5.0.4 on 2026-03-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_remove_grupo_tipos_objetivo'),
        ('gerencia', '0022_alter_objetivo_unique_together'),
    ]
    