# Generated by Django 5.0.4 on 2025-12-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonia',
            name='tiene_relevamiento',
            field=models.BooleanField(default=False, verbose_name='¿Tiene relevamiento previo?'),
        ),
    ]
