# Generated by Django 5.0.4 on 2025-10-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['codigo'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
