# Generated by Django 5.0.4 on 2025-10-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_departamento_options_alter_departamento_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterUniqueTogether(
            name='colonia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='objetivo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colonia',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distrito',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together={('departamento', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='objetivo',
            unique_together={('area', 'codigo')},
        ),
    ]
