# Generated by Django 5.0.4 on 2025-10-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together={('nombre', 'departamento')},
        ),
        migrations.AlterField(
            model_name='distrito',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='colonia',
            unique_together={('nombre',)},
        ),
    ]
