# Generated by Django 5.0.4 on 2025-10-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_distrito_unique_together_alter_distrito_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='codigo',
        ),
        migrations.AlterUniqueTogether(
            name='objetivo',
            unique_together={('area', 'nombre')},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='codigo',
        ),
    ]
