# Generated by Django 5.0.4 on 2025-10-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_area_codigo_remove_colonia_codigo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objetivo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colonia',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='distrito',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='objetivo',
            unique_together={('area', 'codigo')},
        ),
    ]
