# Generated by Django 5.0.4 on 2025-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_objetivo_unique_together_area_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
