# Generated by Django 5.0.4 on 2025-11-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_distrito_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['codigo', 'nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
