# Generated by Django 5.0.4 on 2025-11-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together={('codigo', 'departamento')},
        ),
    ]
