# Generated by Django 5.0.4 on 2025-11-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_distrito_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colonia',
            unique_together=set(),
        ),
    ]
