# Generated by Django 5.0.4 on 2025-11-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_colonia_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
