# Generated by Django 5.0.4 on 2025-12-31 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_add_creado_por_field'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol',
            name='grupo_django',
            field=models.OneToOneField(blank=True, help_text='Grupo de Django sincronizado con este rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Grupo de Django asociado'),
        ),
        migrations.AddField(
            model_name='user',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Color en formato hexadecimal (ej: #007bff)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='grupos de django'),
        ),
    ]
