# Generated by Django 5.0.4 on 2025-12-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_rol_actualizado_rol_creado_rol_grupo_django_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='grupos'),
        ),
    ]
