# Generated by Django 5.0.4 on 2026-01-10 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Grupo')),
                ('descripcion', models.TextField(blank=True, help_text='Propósito u objetivo del grupo', verbose_name='Descripción')),
                ('color', models.CharField(default='#6c757d', help_text='Color identificativo (formato hexadecimal)', max_length=20)),
                ('es_departamento', models.BooleanField(default=False, help_text='Marcar si representa un departamento organizacional', verbose_name='¿Es departamento?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('lider', models.ForeignKey(blank=True, help_text='Usuario responsable del grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Líder del grupo')),
                ('roles_asociados', models.ManyToManyField(blank=True, help_text='Roles que suelen tener los usuarios de este grupo', related_name='grupos_asociados', to='administrador.rol', verbose_name='Roles comúnmente asignados')),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Selecciona los usuarios que pertenecen a este grupo', related_name='grupos_pertenece', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios en el grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nombre'],
                'permissions': [('gestionar_grupos', 'Puede gestionar grupos y asignaciones')],
            },
        ),
    ]
