# Generated by Django 5.0.4 on 2026-01-11 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupo_analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_analisis', to='administrador.grupo', verbose_name='Grupo para Análisis')),
                ('grupo_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_campo', to='administrador.grupo', verbose_name='Grupo para Campo')),
                ('grupo_monitoreo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_monitoreo', to='administrador.grupo', verbose_name='Grupo para Monitoreo')),
                ('grupo_sig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_sig', to='administrador.grupo', verbose_name='Grupo para SIG')),
            ],
            options={
                'verbose_name': 'Flujo de Trabajo',
                'verbose_name_plural': 'Flujos de Trabajo',
            },
        ),
    ]
