# Generated by Django 5.0.4 on 2026-02-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_flujotrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='tipos_objetivo',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de objetivo que maneja este grupo', verbose_name='Tipos de Objetivo'),
        ),
    ]
