# Generated by Django 5.0.4 on 2026-02-23 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_grupo_tipos_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Colonias Relevadas, Planos Aprobados, etc.', max_length=200, verbose_name='Nombre del Tipo de Objetivo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de objetivo', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_objetivo_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_objetivo_list', to='administrador.grupo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Tipo de Objetivo',
                'verbose_name_plural': 'Tipos de Objetivo',
                'ordering': ['grupo__nombre', 'nombre'],
                'unique_together': {('grupo', 'nombre')},
            },
        ),
    ]
