# Generated by Django 5.0.4 on 2026-02-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_tipoobjetivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='tipos_objetivo',
        ),
    ]
