# Generated by Django 5.0.4 on 2026-01-24 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerencia', '0006_solicitudrelevamiento_prioridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecatArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('precat', 'Archivo Precat (ZIP/RAR)'), ('planos', 'Planos de Referencia (PDF)')], max_length=20, verbose_name='Tipo de Archivo')),
                ('archivo', models.FileField(help_text='Formatos permitidos: .zip, .rar para Precat; .pdf para Planos', upload_to='precat/%Y/%m/%d/', verbose_name='Archivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Digitalizador')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precat_archivos', to='gerencia.solicitudrelevamiento', verbose_name='Solicitud de Relevamiento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precat_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo de Precat',
                'verbose_name_plural': 'Archivos de Precat',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
