# Generated by Django 5.0.4 on 2026-01-25 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalizador', '0001_initial'),
        ('gerencia', '0006_solicitudrelevamiento_prioridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='precatarchivo',
            name='archivo',
            field=models.FileField(help_text='Formatos permitidos: .zip, .rar, .7z para Precat; .pdf para Planos', upload_to='precat/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='precatarchivo',
            name='tipo_archivo',
            field=models.CharField(choices=[('precat', 'Archivo Precat (ZIP/RAR/7Z)'), ('planos', 'Planos de Referencia (PDF)')], max_length=20, verbose_name='Tipo de Archivo'),
        ),
        migrations.AddIndex(
            model_name='precatarchivo',
            index=models.Index(fields=['solicitud', 'tipo_archivo'], name='digitalizad_solicit_905b83_idx'),
        ),
        migrations.AddIndex(
            model_name='precatarchivo',
            index=models.Index(fields=['subido_por', 'fecha_subida'], name='digitalizad_subido__fda488_idx'),
        ),
    ]
