# Generated by Django 5.0.4 on 2026-02-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalizador', '0002_alter_precatarchivo_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precatarchivo',
            name='calles',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Calles'),
        ),
        migrations.AddField(
            model_name='precatarchivo',
            name='campos_comunales',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Campos comunales'),
        ),
        migrations.AddField(
            model_name='precatarchivo',
            name='hectareas_aprox',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Hectáreas aproximadas'),
        ),
        migrations.AddField(
            model_name='precatarchivo',
            name='lotes_digitalizados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lotes digitalizados'),
        ),
        migrations.AddField(
            model_name='precatarchivo',
            name='metros_aprox',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Metros aproximados'),
        ),
        migrations.AddField(
            model_name='precatarchivo',
            name='reservas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reservas'),
        ),
        migrations.AlterField(
            model_name='precatarchivo',
            name='archivo',
            field=models.FileField(help_text='Formatos permitidos: .zip, .rar, .7z para Precat; .pdf, .jpg, .jpeg, .png para Planos/Imágenes', upload_to='precat/%Y/%m/%d/', verbose_name='Archivo'),
        ),
    ]
