# Generated by Django 5.0.4 on 2025-09-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-creado']},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('SUCCESS', 'Éxito'), ('ERROR', 'Error')], default='INFO', max_length=20),
        ),
    ]
