# Generated by Django 5.0.4 on 2025-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
