# Generated by Django 5.0.4 on 2026-02-08 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerencia', '0010_alter_solicitudrelevamiento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoRelevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del equipo')),
                ('tipo', models.CharField(choices=[('completo', 'Equipo Completo'), ('rapido', 'Equipo Rápido'), ('especial', 'Equipo Especial')], default='completo', max_length=20)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_campo', 'En Campo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('vehiculos', models.TextField(blank=True, verbose_name='Vehículos asignados')),
                ('equipos', models.TextField(blank=True, verbose_name='Equipos y materiales')),
                ('max_encuestadores', models.IntegerField(default=4, verbose_name='Máximo de encuestadores')),
                ('activo', models.BooleanField(default=True, verbose_name='Equipo activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('choferes', models.ManyToManyField(blank=True, related_name='equipos_chofer', to=settings.AUTH_USER_MODEL, verbose_name='Choferes')),
                ('coordinador_campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_coordinados', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador de Campo')),
                ('encuestadores', models.ManyToManyField(blank=True, related_name='equipos_encuestador', to=settings.AUTH_USER_MODEL, verbose_name='Encuestadores')),
                ('subcoordinadores', models.ManyToManyField(blank=True, related_name='equipos_subcoordinados', to=settings.AUTH_USER_MODEL, verbose_name='Subcoordinadores')),
            ],
            options={
                'verbose_name': 'Equipo de Relevamiento',
                'verbose_name_plural': 'Equipos de Relevamiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('asignada', 'Asignada a Equipos'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='generada', max_length=20)),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('fecha_inicio_planeada', models.DateField(verbose_name='Fecha de inicio planeada')),
                ('fecha_fin_planeada', models.DateField(verbose_name='Fecha de fin planeada')),
                ('fecha_inicio_real', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio real')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha de fin real')),
                ('meta_encuestas', models.IntegerField(default=0, verbose_name='Meta de encuestas')),
                ('encuestas_completadas', models.IntegerField(default=0, verbose_name='Encuestas completadas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('instrucciones_especiales', models.TextField(blank=True, verbose_name='Instrucciones especiales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('coordinador_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_coordinadas', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador Responsable')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('equipos_asignados', models.ManyToManyField(blank=True, related_name='ordenes_trabajo', to='coordinacion.equiporelevamiento', verbose_name='Equipos asignados')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='gerencia.solicitudrelevamiento', verbose_name='Solicitud de origen')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision', models.FloatField(blank=True, help_text='Precisión en metros', null=True)),
                ('estado_actual', models.CharField(max_length=50, verbose_name='Estado actual')),
                ('bateria_dispositivo', models.IntegerField(blank=True, null=True, verbose_name='Batería (%)')),
                ('senal_celular', models.IntegerField(blank=True, null=True, verbose_name='Señal celular')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='coordinacion.equiporelevamiento')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='coordinacion.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Punto de Monitoreo',
                'verbose_name_plural': 'Puntos de Monitoreo',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicio', 'Inicio de Jornada'), ('actividad', 'Actividad Normal'), ('problema', 'Problema/Incidente'), ('cierre', 'Cierre de Jornada')], max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ubicacion_texto', models.CharField(blank=True, max_length=255)),
                ('actividades_realizadas', models.TextField(verbose_name='Actividades realizadas')),
                ('encuestas_completadas', models.IntegerField(default=0)),
                ('problemas_encontrados', models.TextField(blank=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('fotos', models.TextField(blank=True, help_text='URLs de fotos separadas por comas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_campo', to='coordinacion.equiporelevamiento')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_campo', to='coordinacion.ordentrabajo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_campo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Campo',
                'verbose_name_plural': 'Registros de Campo',
                'ordering': ['-fecha_registro', '-hora_inicio'],
            },
        ),
    ]
