# Generated by Django 5.0.4 on 2026-02-19 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocampo',
            name='fotos',
        ),
    ]
