# Generated by Django 5.0.4 on 2026-02-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0002_remove_registrocampo_fotos'),
        ('gerencia', '0012_alter_solicitudrelevamiento_numero_orden_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Es la orden vigente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='gerencia.solicitudrelevamiento', verbose_name='Solicitud de origen'),
        ),
    ]
