# Generated by Django 5.0.4 on 2026-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0003_ordentrabajo_activa_alter_ordentrabajo_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
    ]
