# Generated by Django 5.0.4 on 2026-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0004_ordentrabajo_motivo_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('generada', 'Generada'), ('asignada', 'Asignada a Equipos'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reactivado', 'Reactivado')], default='generada', max_length=20),
        ),
    ]
