# Generated by Django 5.0.4 on 2026-02-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0005_alter_ordentrabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='formulario_habilitado',
            field=models.BooleanField(default=False, help_text='El coordinador de campo debe habilitar el formulario para que los encuestadores puedan crear relevamientos', verbose_name='Formulario habilitado para encuestadores'),
        ),
    ]
