# Generated by Django 5.0.4 on 2026-02-28 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerencia', '0021_remove_solicitudrelevamiento_usuario_digitalizador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDigitalizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_digitalizador', to='gerencia.solicitudrelevamiento', verbose_name='Solicitud')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
            ],
            options={
                'verbose_name': 'Asignación a digitalizador',
                'verbose_name_plural': 'Asignaciones a digitalizador',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
