# Generated by Django 5.0.4 on 2026-02-22 16:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_colonia_tiene_relevamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ci', models.CharField(blank=True, max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('parentesco', models.CharField(blank=True, max_length=100)),
                ('relacion_con_lote', models.CharField(blank=True, max_length=200)),
                ('escolaridad', models.CharField(blank=True, max_length=200)),
                ('grado_ano', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar_atencion', models.CharField(blank=True, max_length=200)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_salud', to='relevamiento.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Relevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana', models.CharField(blank=True, max_length=50)),
                ('lote_indert', models.CharField(blank=True, max_length=50)),
                ('lote_sirt', models.CharField(blank=True, max_length=50)),
                ('formulario', models.IntegerField(blank=True, null=True)),
                ('observacion_encuesta', models.TextField(blank=True)),
                ('uso_lote', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('acuario_forestal', 'Acuario/Forestal'), ('forestal_nativa', 'Forestal - Nativa'), ('barbecho_descanso', 'Barbecho - Descanso'), ('abandonado', 'Abandonado'), ('comercial', 'Comercial'), ('industrial', 'Industrial'), ('local_politico', 'Local Político'), ('local_recreativo', 'Local Recreativo')], max_length=50), blank=True, default=list, null=True, size=None)),
                ('nro_titulo', models.CharField(blank=True, max_length=200)),
                ('tipo_lote', models.CharField(blank=True, choices=[('agricola', 'Agrícola'), ('quinta', 'Quinta'), ('urbana', 'Urbana')], max_length=20)),
                ('condicion_vivienda', models.CharField(blank=True, choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('sin_vivienda', 'Sin vivienda')], max_length=20)),
                ('condicion_encuestado', models.CharField(blank=True, choices=[('titular', 'Titular'), ('ocupante', 'Ocupante'), ('pariente', 'Pariente o no pariente'), ('otro', 'Otro')], max_length=20)),
                ('superficie_ha', models.FloatField(blank=True, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=200)),
                ('vive_en_lote', models.BooleanField(default=False)),
                ('residencia_manzana', models.CharField(blank=True, max_length=50)),
                ('residencia_lote', models.CharField(blank=True, max_length=50)),
                ('quien_es_el_ocupante', models.CharField(blank=True, max_length=200)),
                ('parentesco', models.CharField(blank=True, max_length=200)),
                ('produccion_agricola_ha', models.FloatField(blank=True, default=0)),
                ('produccion_ganadera_ha', models.FloatField(blank=True, default=0)),
                ('reforestado_ha', models.FloatField(blank=True, default=0)),
                ('bosque_natural_ha', models.FloatField(blank=True, default=0)),
                ('barbecho_ha', models.FloatField(blank=True, default=0)),
                ('mejoras', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('galpon', 'Galpón'), ('corrales', 'Corrales'), ('bretes', 'Bretes'), ('represa', 'Represa'), ('sanitarios', 'Instalaciones Sanitarias'), ('pozo', 'Pozo'), ('tajamares', 'Tajamares'), ('mangas', 'Mangas'), ('cercado_perimetral', 'Cercado Perimetral'), ('silos', 'Silos'), ('canales_riego', 'Canales de Irrigación'), ('energia_electrica', 'Energía Eléctrica'), ('agua_potable', 'Agua Potable')], max_length=50), blank=True, default=list, null=True, size=None)),
                ('estado_entrevista', models.CharField(blank=True, choices=[('completa', 'Completa'), ('rechazo', 'Rechazo'), ('parcial', 'Parcial'), ('en_conflicto', 'En Conflicto')], max_length=20)),
                ('firmo_solicitud', models.BooleanField(default=False)),
                ('modificaciones_post', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cambio_recurrente', 'Cambio de Recurrente'), ('correccion_superficie', 'Corrección de Superficie'), ('ampliacion', 'Ampliación')], max_length=50), blank=True, default=list, help_text='Lista de claves de modificaciones', null=True, size=None)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colonia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.colonia')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionGanadera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('relevamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones_ganaderas', to='relevamiento.relevamiento')),
            ],
        ),
        migrations.CreateModel(
            name='OcupanteAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anterior', models.CharField(blank=True, max_length=200)),
                ('ci_anterior', models.CharField(blank=True, max_length=100)),
                ('relevamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupantes_anteriores', to='relevamiento.relevamiento')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='relevamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='relevamiento.relevamiento'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recibo', 'Recibos'), ('constancia_ocupacion', 'Constancia de ocupacion'), ('plano', 'Plano'), ('transferencia', 'Transferencia'), ('otros', 'Otros')], max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='relevamiento/docs/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('relevamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='relevamiento.relevamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_siembra', models.CharField(choices=[('temporal', 'Temporal'), ('permanente', 'Permanente')], max_length=20)),
                ('hectareas', models.FloatField()),
                ('relevamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='relevamiento.relevamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paredes', models.CharField(blank=True, choices=[('ladrillo', 'Ladrillo'), ('madera', 'Madera'), ('adobe', 'Adobe'), ('mixto', 'Mixto'), ('otro', 'Otro')], max_length=20)),
                ('piso', models.CharField(blank=True, choices=[('ceramica', 'Cerámica'), ('cemento', 'Cemento'), ('tierra', 'Tierra'), ('madera', 'Madera'), ('otro', 'Otro')], max_length=20)),
                ('techo', models.CharField(blank=True, choices=[('chapa', 'Chapa de Zinc'), ('teja', 'Teja'), ('paja', 'Paja'), ('losa', 'Losa'), ('otro', 'Otro')], max_length=20)),
                ('piezas', models.IntegerField(blank=True, null=True)),
                ('agua_proviene', models.CharField(blank=True, choices=[('pozo', 'Pozo'), ('red_publica', 'Red Pública'), ('arroyo', 'Arroyo/Río'), ('aljibe', 'Aljibe'), ('otro', 'Otro')], max_length=20)),
                ('tipo_bano', models.CharField(blank=True, choices=[('letrina', 'Letrina'), ('pozo_ciego', 'Baño con Pozo Ciego'), ('alcantarillado', 'Baño con Alcantarillado'), ('no_tiene', 'No Tiene')], max_length=20)),
                ('equipamientos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('energia_electrica', 'Energía Eléctrica'), ('agua_corriente', 'Agua Corriente'), ('cocina', 'Cocina'), ('bano', 'Baño'), ('telefono_fijo', 'Teléfono Fijo'), ('internet', 'Internet')], max_length=50), blank=True, default=list, help_text='Lista de equipamientos: energia, agua, cocina, baño, telefono, internet', null=True, size=None)),
                ('relevamiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivienda', to='relevamiento.relevamiento')),
            ],
        ),
    ]
