# Generated by Django 5.0.4 on 2026-02-22 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0005_alter_ordentrabajo_estado'),
        ('relevamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamiento',
            name='encuestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relevamientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Encuestador'),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relevamientos', to='coordinacion.ordentrabajo', verbose_name='Orden de Trabajo'),
        ),
    ]
