# Generated by Django 5.0.4 on 2026-02-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0005_alter_ordentrabajo_estado'),
        ('relevamiento', '0002_relevamiento_encuestador_relevamiento_orden_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevamiento',
            name='condicion_vivienda',
            field=models.CharField(blank=True, choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('sin_vivienda', 'Sin vivienda'), ('servicio', 'Servicio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relevamiento',
            name='orden_trabajo',
            field=models.ForeignKey(help_text='Todo relevamiento debe estar asociado a una orden de trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='relevamientos', to='coordinacion.ordentrabajo', verbose_name='Orden de Trabajo'),
        ),
    ]
