# Generated by Django 5.0.4 on 2026-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relevamiento', '0003_alter_relevamiento_condicion_vivienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamiento',
            name='archivo_subcoordinador',
            field=models.FileField(blank=True, help_text='Archivo comprimido (.zip, .rar, .7z, etc.) subido por el subcoordinador', null=True, upload_to='relevamiento/archivos_subcoordinador/', verbose_name='Archivo del Subcoordinador'),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='fecha_subida_archivo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Subida del Archivo'),
        ),
    ]
