# Generated by Django 5.0.4 on 2026-02-24 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacion', '0006_ordentrabajo_formulario_habilitado'),
        ('relevamiento', '0004_relevamiento_archivo_subcoordinador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSubcoordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='vivser_relevamiento/', verbose_name='Archivo Comprimido')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subcoordinador', to='coordinacion.ordentrabajo', verbose_name='Orden de Trabajo')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo de Subcoordinador',
                'verbose_name_plural': 'Archivos de Subcoordinadores',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
