# Generated by Django 5.0.4 on 2026-02-25 03:50

import django.db.models.deletion
import relevamiento.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relevamiento', '0005_archivosubcoordinador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosubcoordinador',
            name='archivo',
            field=models.FileField(help_text='Se organizará automáticamente en: relevamiento/{depto}/{distrito}/{colonia}/{fecha_OT}/', upload_to=relevamiento.models.path_relevamiento_upload, verbose_name='Archivo Comprimido'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, help_text='Se guardará en: relevamiento/{depto}/{distrito}/{colonia}/{fecha_OT}/FOTOS/', null=True, upload_to=relevamiento.models.path_relevamiento_fotos_upload),
        ),
        migrations.AlterField(
            model_name='relevamiento',
            name='archivo_subcoordinador',
            field=models.FileField(blank=True, help_text='Archivo comprimido (.zip, .rar, .7z, etc.) - Se organiza en: relevamiento/{depto}/{distrito}/{colonia}/{fecha_OT}/', null=True, upload_to=relevamiento.models.path_relevamiento_upload, verbose_name='Archivo del Subcoordinador'),
        ),
        migrations.CreateModel(
            name='FotoRelevamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Se guardará en: relevamiento/{depto}/{distrito}/{colonia}/{fecha_OT}/FOTOS/', upload_to=relevamiento.models.path_relevamiento_fotos_upload, verbose_name='Fotografía')),
                ('tipo_foto', models.CharField(choices=[('vivienda_frente', 'Vivienda - Frente'), ('vivienda_lateral', 'Vivienda - Lateral'), ('vivienda_fondo', 'Vivienda - Fondo'), ('lote_general', 'Vista General del Lote'), ('mejoras', 'Mejoras/Construcciones'), ('cultivos', 'Cultivos'), ('documento', 'Documento/Título'), ('familia', 'Familia'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo de Foto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captura')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada GPS de la foto', max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada GPS de la foto', max_digits=11, null=True, verbose_name='Longitud')),
                ('encuestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_tomadas', to=settings.AUTH_USER_MODEL, verbose_name='Encuestador')),
                ('relevamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='relevamiento.relevamiento', verbose_name='Relevamiento')),
            ],
            options={
                'verbose_name': 'Foto de Relevamiento',
                'verbose_name_plural': 'Fotos de Relevamiento',
                'ordering': ['-fecha_captura'],
            },
        ),
    ]
