# Generated by Django 5.0.4 on 2026-03-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relevamiento', '0006_alter_archivosubcoordinador_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevamiento',
            name='tipo_lote',
            field=models.CharField(blank=True, choices=[('agricola', 'Agrícola'), ('quinta', 'Quinta'), ('urbano', 'Urbano')], max_length=20),
        ),
    ]
