# Generated by Django 5.0.4 on 2026-03-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relevamiento', '0007_alter_relevamiento_tipo_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevamiento',
            name='cedula_ocupante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relevamiento',
            name='sexo_ocupante',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='relevamiento',
            name='formulario',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
